---
build_from:
  aarch64: docker.1ms.run/home-assistant/aarch64-base:3.19
  amd64: docker.1ms.run/home-assistant/amd64-base:3.19
  armhf: docker.1ms.run/home-assistant/armhf-base:3.19
  armv7: docker.1ms.run/home-assistant/armv7-base:3.19
  i386: docker.1ms.run/home-assistant/i386-base:3.19
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
