---
build_from:
  aarch64: docker.1ms.run/home-assistant/aarch64-base-debian:bookworm
  amd64: docker.1ms.run/home-assistant/amd64-base-debian:bookworm
  armhf: docker.1ms.run/home-assistant/armhf-base-debian:bookworm
  armv7: docker.1ms.run/home-assistant/armv7-base-debian:bookworm
  i386: docker.1ms.run/home-assistant/i386-base-debian:bookworm
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  LIBWEBSOCKET_VERSION: 4.3.3
  MOSQUITTO_VERSION: 2.0.20
  MOSQUITTO_AUTH_VERSION: 2.1.0
